/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BytesLike,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { PayableOverrides } from "../../../common";
import type {
  AccountManagerProxy,
  AccountManagerProxyInterface,
} from "../../../contracts/proxy/AccountManagerProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_impl",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "AddressEmptyCode",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "ERC1967InvalidImplementation",
    type: "error",
  },
  {
    inputs: [],
    name: "ERC1967NonPayable",
    type: "error",
  },
  {
    inputs: [],
    name: "FailedCall",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
] as const;

const _bytecode =
  "0x608060408181526102fc803803809161001882866101d5565b843982019181818403126101d05780516001600160a01b03811693908481036101d0576020948584015160018060401b03948582116101d0570183601f820112156101d0578051610068816101f8565b94610075885196876101d5565b8186528882840101116101d057879160005b8281106101bd5750509060009185010152813b156101a6577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc80546001600160a01b031916821790558451907fbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b600080a28251156101895750600080838761013b95519101845af43d15610181573d91610120836101f8565b9261012d875194856101d5565b83523d60008885013e610213565b505b81519267555b77437fa44e3d8185015283528183019283109083111761016b57819052608590816102778239f35b634e487b7160e01b600052604160045260246000fd5b606091610213565b91505034610197575061013d565b63b398979f60e01b8152600490fd5b602490855190634c9c8ce360e01b82526004820152fd5b8181018401518782018501528301610087565b600080fd5b601f909101601f19168101906001600160401b0382119082101761016b57604052565b6001600160401b03811161016b57601f01601f191660200190565b9061023a575080511561022857805190602001fd5b60405163d6bda27560e01b8152600490fd5b8151158061026d575b61024b575090565b604051639996b31560e01b81526001600160a01b039091166004820152602490fd5b50803b1561024356fe60806040527f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc54600090819081906001600160a01b0316368280378136915af43d82803e15604b573d90f35b3d90fdfea2646970667358221220b045f5f582637b7b892ba04df1dc9630cbb7df2fbf24a51650b2333cdff228e264736f6c63430008160033";

type AccountManagerProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AccountManagerProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AccountManagerProxy__factory extends ContractFactory {
  constructor(...args: AccountManagerProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _impl: AddressLike,
    _data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_impl, _data, overrides || {});
  }
  override deploy(
    _impl: AddressLike,
    _data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ) {
    return super.deploy(_impl, _data, overrides || {}) as Promise<
      AccountManagerProxy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AccountManagerProxy__factory {
    return super.connect(runner) as AccountManagerProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AccountManagerProxyInterface {
    return new Interface(_abi) as AccountManagerProxyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AccountManagerProxy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AccountManagerProxy;
  }
}
