/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAccount__factory } from "./IAccount__factory";
export { IAccountFactory__factory } from "./IAccountFactory__factory";
